# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1b0eba07c798ec94c371c65d94d2da0db6b5627442056a790c6383bdbeec76c747d8098d431e5d0b9b7748dfa7f0b3edf316efbfa52ae24ed172bc5b9ebf9d1

test:
  secret_key_base: ae7398dcb88cdaec16e3830d98ea498cf30d5fb8351c3e8d693d5e6edb10294ff021b96ae7c56f7020873602c89fc6d331b59d8d4f37e08c614b2a4c1d193153

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
